[2025-04-05T10:35:17.469+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: alpha_vantage_pipeline.load_to_bq manual__2025-04-05T08:56:21.946265+00:00 [queued]>
[2025-04-05T10:35:17.560+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: alpha_vantage_pipeline.load_to_bq manual__2025-04-05T08:56:21.946265+00:00 [queued]>
[2025-04-05T10:35:17.565+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-05T10:35:17.565+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2025-04-05T10:35:17.567+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-05T10:35:17.728+0000] {taskinstance.py:1300} INFO - Executing <Task(GCSToBigQueryOperator): load_to_bq> on 2025-04-05 08:56:21.946265+00:00
[2025-04-05T10:35:17.815+0000] {standard_task_runner.py:55} INFO - Started process 177 to run task
[2025-04-05T10:35:17.836+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'alpha_vantage_pipeline', 'load_to_bq', 'manual__2025-04-05T08:56:21.946265+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/alpha_vantage_pipeline.py', '--cfg-path', '/tmp/tmpcnsve205']
[2025-04-05T10:35:17.860+0000] {standard_task_runner.py:83} INFO - Job 83: Subtask load_to_bq
[2025-04-05T10:35:18.546+0000] {task_command.py:388} INFO - Running <TaskInstance: alpha_vantage_pipeline.load_to_bq manual__2025-04-05T08:56:21.946265+00:00 [running]> on host f3c96279a1c9
[2025-04-05T10:35:19.231+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=alpha_vantage_pipeline
AIRFLOW_CTX_TASK_ID=load_to_bq
AIRFLOW_CTX_EXECUTION_DATE=2025-04-05T08:56:21.946265+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-05T08:56:21.946265+00:00
[2025-04-05T10:35:19.325+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-04-05T10:35:19.333+0000] {gcs_to_bigquery.py:377} INFO - Using existing BigQuery table for storing data...
[2025-04-05T10:35:19.335+0000] {credentials_provider.py:323} INFO - Getting connection using `google.auth.default()` since no key file is defined for hook.
[2025-04-05T10:35:19.923+0000] {gcs_to_bigquery.py:381} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'finflow-455108', 'datasetId': 'my_dataset', 'tableId': 'final_table'}, 'sourceFormat': 'PARQUET', 'sourceUris': ['gs://finflow-455108-data-lake/intermediate/alpha_vantage/*.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False}}
[2025-04-05T10:35:19.943+0000] {bigquery.py:1542} INFO - Inserting job ***_alpha_vantage_pipeline_load_to_bq_2025_04_05T08_56_21_946265_00_00_cbbe53f8e2319a2db88d0ba2308bffe6
[2025-04-05T10:35:22.164+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 440, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: Uris gs://finflow-455108-data-lake/intermediate/alpha_vantage/*.csv
[2025-04-05T10:35:22.233+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=alpha_vantage_pipeline, task_id=load_to_bq, execution_date=20250405T085621, start_date=20250405T103517, end_date=20250405T103522
[2025-04-05T10:35:22.368+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 83 for task load_to_bq (404 Not found: Uris gs://finflow-455108-data-lake/intermediate/alpha_vantage/*.csv; 177)
[2025-04-05T10:35:22.465+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-04-05T10:35:22.556+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
