[2025-04-05T08:46:57.984+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: alpha_vantage_pipeline.load_to_bq manual__2025-04-05T08:46:39.256850+00:00 [queued]>
[2025-04-05T08:46:57.992+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: alpha_vantage_pipeline.load_to_bq manual__2025-04-05T08:46:39.256850+00:00 [queued]>
[2025-04-05T08:46:57.992+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-05T08:46:57.992+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-04-05T08:46:57.992+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-05T08:46:58.003+0000] {taskinstance.py:1300} INFO - Executing <Task(GCSToBigQueryOperator): load_to_bq> on 2025-04-05 08:46:39.256850+00:00
[2025-04-05T08:46:58.011+0000] {standard_task_runner.py:55} INFO - Started process 263 to run task
[2025-04-05T08:46:58.014+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'alpha_vantage_pipeline', 'load_to_bq', 'manual__2025-04-05T08:46:39.256850+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/alpha_vantage_pipeline.py', '--cfg-path', '/tmp/tmppowvgbtv']
[2025-04-05T08:46:58.016+0000] {standard_task_runner.py:83} INFO - Job 69: Subtask load_to_bq
[2025-04-05T08:46:58.082+0000] {task_command.py:388} INFO - Running <TaskInstance: alpha_vantage_pipeline.load_to_bq manual__2025-04-05T08:46:39.256850+00:00 [running]> on host 072190d48754
[2025-04-05T08:46:58.151+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=alpha_vantage_pipeline
AIRFLOW_CTX_TASK_ID=load_to_bq
AIRFLOW_CTX_EXECUTION_DATE=2025-04-05T08:46:39.256850+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-05T08:46:39.256850+00:00
[2025-04-05T08:46:58.169+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-04-05T08:46:58.171+0000] {gcs_to_bigquery.py:377} INFO - Using existing BigQuery table for storing data...
[2025-04-05T08:46:58.173+0000] {credentials_provider.py:323} INFO - Getting connection using `google.auth.default()` since no key file is defined for hook.
[2025-04-05T08:46:58.222+0000] {gcs_to_bigquery.py:381} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'your_project', 'datasetId': 'your_dataset', 'tableId': 'final_table'}, 'sourceFormat': 'PARQUET', 'sourceUris': ['gs://your-bucket/intermediate/alpha_vantage/*.parquet'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False}}
[2025-04-05T08:46:58.223+0000] {bigquery.py:1542} INFO - Inserting job ***_alpha_vantage_pipeline_load_to_bq_2025_04_05T08_46_39_256850_00_00_704d679c2a2a57b06a203997f4570712
[2025-04-05T08:46:59.052+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 382, in execute
    job = self._submit_job(self.hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 309, in _submit_job
    nowait=True,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 462, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1545, in insert_job
    job._begin()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 518, in _begin
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/finflow-455108/jobs?prettyPrint=false: Invalid project ID 'your_project'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.
[2025-04-05T08:46:59.070+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=alpha_vantage_pipeline, task_id=load_to_bq, execution_date=20250405T084639, start_date=20250405T084657, end_date=20250405T084659
[2025-04-05T08:46:59.089+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 69 for task load_to_bq (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/finflow-455108/jobs?prettyPrint=false: Invalid project ID 'your_project'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.; 263)
[2025-04-05T08:46:59.111+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-04-05T08:46:59.134+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
