[2025-04-06T00:54:44.486+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: alpha_vantage_pipeline.load_to_bq manual__2025-04-06T00:54:26.222482+00:00 [queued]>
[2025-04-06T00:54:44.493+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: alpha_vantage_pipeline.load_to_bq manual__2025-04-06T00:54:26.222482+00:00 [queued]>
[2025-04-06T00:54:44.493+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-06T00:54:44.494+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-04-06T00:54:44.494+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-06T00:54:44.504+0000] {taskinstance.py:1300} INFO - Executing <Task(GCSToBigQueryOperator): load_to_bq> on 2025-04-06 00:54:26.222482+00:00
[2025-04-06T00:54:44.512+0000] {standard_task_runner.py:55} INFO - Started process 306 to run task
[2025-04-06T00:54:44.515+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'alpha_vantage_pipeline', 'load_to_bq', 'manual__2025-04-06T00:54:26.222482+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/alpha_vantage_pipeline.py', '--cfg-path', '/tmp/tmp3npx0rlf']
[2025-04-06T00:54:44.516+0000] {standard_task_runner.py:83} INFO - Job 250: Subtask load_to_bq
[2025-04-06T00:54:44.597+0000] {task_command.py:388} INFO - Running <TaskInstance: alpha_vantage_pipeline.load_to_bq manual__2025-04-06T00:54:26.222482+00:00 [running]> on host 6f962c669fc2
[2025-04-06T00:54:44.659+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=alpha_vantage_pipeline
AIRFLOW_CTX_TASK_ID=load_to_bq
AIRFLOW_CTX_EXECUTION_DATE=2025-04-06T00:54:26.222482+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-06T00:54:26.222482+00:00
[2025-04-06T00:54:44.668+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-04-06T00:54:44.669+0000] {gcs_to_bigquery.py:377} INFO - Using existing BigQuery table for storing data...
[2025-04-06T00:54:44.669+0000] {credentials_provider.py:323} INFO - Getting connection using `google.auth.default()` since no key file is defined for hook.
[2025-04-06T00:54:44.716+0000] {gcs_to_bigquery.py:381} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'finflow-455108', 'datasetId': 'my_dataset', 'tableId': 'final_table'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://finflow-455108-data-lake/raw/alpha_vantage/*/*.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2025-04-06T00:54:44.716+0000] {bigquery.py:1542} INFO - Inserting job ***_alpha_vantage_pipeline_load_to_bq_2025_04_06T00_54_26_222482_00_00_312c59b6ab05c446e1419e1a786c3394
[2025-04-06T00:54:45.901+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 440, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: Uris gs://finflow-455108-data-lake/raw/alpha_vantage/*/*.csv
[2025-04-06T00:54:45.911+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=alpha_vantage_pipeline, task_id=load_to_bq, execution_date=20250406T005426, start_date=20250406T005444, end_date=20250406T005445
[2025-04-06T00:54:45.920+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 250 for task load_to_bq (404 Not found: Uris gs://finflow-455108-data-lake/raw/alpha_vantage/*/*.csv; 306)
[2025-04-06T00:54:45.970+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-04-06T00:54:45.998+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
